name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake lcov gcovr libgtest-dev libgmock-dev

      - name: Configure CMake with coverage
        run: cmake -B _build -DBUILD_TESTS=ON -DCMAKE_CXX_FLAGS="--coverage -O0 -g -w"

      - name: Build
        run: cmake --build _build

      - name: Run tests
        working-directory: _build
        run: ctest --verbose

      - name: Install gcovr (if not already)
        run: sudo apt-get install -y gcovr

      - name: Collect coverage with gcovr
        working-directory: _build
        run: |
          gcovr -r .. --gcov-ignore-errors=no_working_dir_found \
            --filter '.*banking/.*' \
            --exclude '.*tests.*' \
            --exclude '.*mocks.*' \
            --exclude '.*print.hpp' \
            --xml coverage.xml

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: _build/coverage.xml
          repo-token: zXEE4h7x4nOKrgunhP3snjm140BLxsT7aoJb
